version: "3.8"
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_USER: ecumenosuser
      POSTGRES_DB: ecumenos_orbis_socius_register_apidb

volumes:
  db:
    driver: local
