// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handlers is an autogenerated mock type for the Handlers type
type Handlers struct {
	mock.Mock
}

// Info provides a mock function with given fields: rw, r
func (_m *Handlers) Info(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// Ping provides a mock function with given fields: rw, r
func (_m *Handlers) Ping(rw http.ResponseWriter, r *http.Request) {
	_m.Called(rw, r)
}

// NewHandlers creates a new instance of Handlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handlers {
	mock := &Handlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
